name: "Check Node.js Version Consistency"
author: "Adriaan van Rossum"
description: "Checks for consistent Node.js versions across various files."
branding:
  icon: "search"
  color: "red"
inputs:
  additional_files:
    description: "Comma separated list additional file paths to check for Node.js version."
    required: false
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "${{ inputs.additional_files }}"
